# Generated by Django 2.1.7 on 2019-03-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField()),
                ('child_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inl.Child1')),
            ],
        ),
        migrations.CreateModel(
            name='Child3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField()),
                ('child_keys', models.ManyToManyField(to='inl.Child2')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='child3',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inl.Master'),
        ),
        migrations.AddField(
            model_name='child2',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inl.Master'),
        ),
        migrations.AddField(
            model_name='child1',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inl.Master'),
        ),
    ]
